name: "Build & Release"

on:
    pull_request:
        branches:
            - master
            - actions
    push:
        branches:
        - master
        - actions

jobs:
    build:
        name: Build & Release
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        
            - name: Set Up Java
              uses: actions/setup-java@v3.12.0
              with:
                distribution: 'oracle'
                java-version: '17'


            - name: Set Up Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.13.0'
                channel: 'stable'


            - name: Install Dependencies
              run: flutter pub get

        #5 run test
            - name: Test flutter app
              run: flutter test

        #6 build apk
            - name: Build APK
              run: flutter build apk --release
